max_execution_time = 300;
short_open_tag = 0;
cgi.fix_pathinfo = 0;

file_uploads = On
upload_max_filesize = 20M;
post_max_size = 25M;
memory_limit = 256M;
error_reporting = E_ALL & ~E_NOTICE & ~E_STRICT & ~E_DEPRECATED;

extension = mysqli;
extension = gd;
extension = imagick.so;

zlib.output_compression = 1;
zlib.output_compression_level = 8;

; [php-opcache]
opcache.enable = 1
opcache.enable_cli = 1
opcache.memory_consumption = 256;
opcache.max_accelerated_files = 2000;
opcache.interned_strings_buffer = 16;
opcache.validate_timestamps = 0;
realpath_cache_size = 4096K;
realpath_cache_ttl = 6000;
opcache.revalidate_freq=0
opcache.fast_shutdown=1

; [php-fpm]
pm = dynamic;
pm.start_servers = 72;
pm.max_children = 200;
pm.max_requests = 600;
pm.max_spare_servers = 192;
pm.min_spare_servers = 32;

display_errors = Off;
display_startup_errors = Off;
log_errors = On;
ignore_repeated_errors = Off;
ignore_repeated_source = Off;
html_errors = Off;
