version: '3'
services:
  frontend:
    restart: unless-stopped
    container_name: damimporter_wp
    build:
      context: .
      dockerfile: ./docker/wp/Dockerfile
      args:
        - UID=${UID:-(id -u)}
        - GID=${GID:-(id -g)}
        - WEBUSER=${WEBUSER:-(id -un)}
        - WEBGROUP=${WEBGROUP:-(id -gn)}
    ports:
      - "${APP_PORT:-9000}:9000"
      - "${APP_SERVER_PORT:-3000}:3000"
      # - "${HOST_PORT:-8080}:80"
    links:
      - database
    depends_on:
      - database
    networks:
      - public
      - internal
    volumes:
      - wp-data:/var/www/html
      - ./wp:/var/www/html/wp-content:delegated
      - ./docker/php/:/usr/local/etc/php/conf.d/
    environment:
      - WORDPRESS_DOMAIN="https://${APP_HOST:-damimporter.localhost}/"
      - WORDPRESS_DB_HOST=${DB_HOST:-database}
      - WORDPRESS_DB_PORT=${DB_PORT:-3306}
      - WORDPRESS_DB_NAME=${DB_NAME:-wordpress}
      - WORDPRESS_DB_USER=${DB_USERNAME:-wpdbuser}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD:-wpdbpassword}
      - WORDPRESS_DEBUG=${WORDPRESS_DEBUG:-true}
      - WP_DEBUG=${WORDPRESS_DEBUG:-true}
      - WP_DEBUG_LOG=${WORDPRESS_DEBUG:-true}
      - WP_DEBUG_DISPLAY=${WORDPRESS_DEBUG:-true}
      - WP_CACHE=true
      - WORDPRESS_CONFIG_EXTRA=
          define('FS_METHOD', 'direct');
          define('WP_ALLOW_REPAIR', 'repair');
          define('WP_HOME', 'https://${APP_HOST:-damimporter.localhost}:${HOST_PORT:-8011}/');
          define('WP_SITEURL', 'https://${APP_HOST:-damimporter.localhost}:${HOST_PORT:-8011}/');
      - TZ=Europe/London

  database:
    container_name: damimporter_db
    image: mariadb:latest
    restart: always
    networks:
      - internal
    # command: [
    #   "--explicit_defaults_for_timestamp"
    # ]
    volumes:
      - ./db:/docker-entrypoint-initdb.d/
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME:-wordpress}
      - MYSQL_USER=${DB_USERNAME:-wpdbuser}
      - MYSQL_PASSWORD=${DB_PASSWORD:-wpdbpassword}
      - TZ=Europe/London

  proxy:
    container_name: damimporter_proxy
    image: nginx:latest
    restart: unless-stopped
    tty: true
    ports:
      # - "${HOST_PORT:-8080}:80"
      - "${HOST_PORT:-8011}:443"
    networks:
      - internal
      - public
    volumes_from:
      - frontend
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d/:ro
      - ./docker/ssl:/etc/ssl:delegated
    environment:
      - NGINX_HOST=${APP_HOST:-damimporter.localhost}
      - NGINX_PORT=443
      - TZ=Europe/London

volumes:
  wp-data:
  db-data:

networks:
  public:
    driver: bridge
  internal:
    driver: bridge

