<?php

declare(strict_types=1);

namespace MariusCucuruz\DAMImporter\Enums;

enum NotificationEnum: string
{
    case NEW_ACCOUNT_CREATION = 'NEW_ACCOUNT_CREATION';
    case RESET_PASSWORD = 'RESET_PASSWORD';
    case PASSWORD_CHANGED = 'PASSWORD_CHANGED';
    case USER_INVITED_TO_TEAM = 'USER_INVITED_TO_TEAM';
    case USER_ACCEPTED_TEAM_INVITE = 'USER_ACCEPTED_TEAM_INVITE';
    case JOINED_NEW_TEAM = 'JOINED_NEW_TEAM';
    case USER_ADDED_CONNECTION = 'USER_ADDED_CONNECTION';
    case USER_REENABLED_CONNECTION = 'USER_REENABLED_CONNECTION';
    case USER_REMOVED_CONNECTION = 'USER_REMOVED_CONNECTION';
    case USER_DISABLED_CONNECTION = 'USER_DISABLED_CONNECTION';
    case USER_DISCONNECTED_CONNECTION = 'USER_DISCONNECTED_CONNECTION';
    case USER_FAULTED_CONNECTION = 'USER_FAULTED_CONNECTION';
    case TEAM_ADDED_CONNECTION = 'TEAM_ADDED_CONNECTION';
    case TEAM_APPROVED_CONNECTION = 'TEAM_APPROVED_CONNECTION';
    case TEAM_REENABLED_CONNECTION = 'TEAM_REENABLED_CONNECTION';
    case TEAM_REMOVED_CONNECTION = 'TEAM_REMOVED_CONNECTION';
    case TEAM_DISABLED_CONNECTION = 'TEAM_DISABLED_CONNECTION';
    case TEAM_DISCONNECTED_CONNECTION = 'TEAM_DISCONNECTED_CONNECTION';
    case TEAM_FAULTED_CONNECTION = 'TEAM_FAULTED_CONNECTION';
    case ASSET_READY_FOR_PLAYBACK = 'ASSET_READY_FOR_PLAYBACK';
    case ASSET_UPLOADED = 'ASSET_UPLOADED';
    case ASSET_COMMENT_REPLY = 'ASSET_COMMENT_REPLY';
    case ASSET_COMMENT_LIKED = 'ASSET_COMMENT_LIKED';
    case ASSET_COMMENT_MENTION = 'ASSET_COMMENT_MENTION';
    case ALL_ASSETS_PROCESSED = 'ALL_ASSETS_PROCESSED';
    case NEW_CONNECTION_SOURCE_INTEGRATION = 'NEW_CONNECTION_SOURCE_INTEGRATION';
    case USER_SHARED_ASSET = 'USER_SHARED_ASSET';
    case WEEKLY_DIGEST = 'WEEKLY_DIGEST';
    case USER_LEFT_TEAM = 'USER_LEFT_TEAM';
}
