resolver  127.0.0.11 valid=10s;  # recover from the backend's IP changing

log_format amplify_ext '$remote_addr - $remote_user [$time_local] "$request" '
                     '$status $body_bytes_sent "$http_referer" '
                     '"$http_user_agent" "$http_x_forwarded_for" '
                     '"$host" sn="$server_name" '
                     'rt=$request_time '
                     'ua="$upstream_addr" us="$upstream_status" '
                     'ut="$upstream_response_time" ul="$upstream_response_length" '
                     'cs=$upstream_cache_status';

server {
    listen 8082;
    listen [::]:8082;

    server_name website.uk www.website.uk;
    server_tokens off;

    return 301 https://www.website.uk$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name www.website.uk website.uk;
    server_tokens off;

    ssl_stapling off;
    ssl_certificate     /etc/letsencrypt/live/localhost.ml.crt;
    ssl_certificate_key /etc/letsencrypt/live/localhost.ml.key;
    ; ssl_certificate     /etc/letsencrypt/live/website.uk/fullchain.pem;
    ; ssl_certificate_key /etc/letsencrypt/live/website.uk/privkey.pem;

    root /var/www/html;
    index index.php;
 
    access_log /var/log/nginx/access.log  amplify_ext;
    error_log  /var/log/nginx/error.log   warn;

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

    location = /humans.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

    location ~ /.well-known/acme-challenge {
        allow all;
        root /var/www/html;
    }

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
         include fastcgi_params;
         fastcgi_split_path_info ^(.+\.php)(/.+)$;
         fastcgi_pass   front:9000;
         fastcgi_index  index.php;
         try_files $uri =404;
         include fastcgi_params;
         fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
         fastcgi_param PATH_INFO $fastcgi_path_info;
         fastcgi_intercept_errors on;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires max;
        log_not_found off;
    }
}
