[PHP]
file_uploads = On
memory_limit = 4G
upload_max_filesize = 0
post_max_size = 0
max_execution_time = 600

[opcache]
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=192
opcache.interned_strings_buffer=16
opcache.max_accelerated_files=4000
opcache.validate_timestamps=0
opcache.revalidate_freq=0
opcache.fast_shutdown=1
